In [1]:
import numpy as np
mat1= np.random.randint(1,10,(3,3))
mat2= np.random.randint(1,10,(3,3))
print("Matrix 1:")
print(mat1)
print("Matrix 2:")
print(mat2)
print()
print('Addition of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1+mat2
print(mat3)
print()
print('Subtraction of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1+mat2
print(mat3)
print()
print('Multiplication of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1*mat2
print(mat3)
print()

mat1= np.random.randint(1,10,(4,3))
mat2= np.random.randint(1,10,(3,2))
print("Matrix 1:")
print(mat1)
print("Matrix 2:")
print(mat2)
print()
print('Element-by-Element Multiplication of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1.dot(mat2)
print(mat3)
print()
print('Displaying Specific Rows and column')
print('---------------------------------------------------------------------------')
print(mat3[1:,1:])


Matrix 1:
[[4 5 5]
 [9 5 7]
 [5 4 5]]
Matrix 2:
[[1 4 9]
 [1 9 5]
 [6 7 2]]

Addition of Two matrices
---------------------------------------------------------------------------
[[ 5  9 14]
 [10 14 12]
 [11 11  7]]

Subtraction of Two matrices
---------------------------------------------------------------------------
[[ 5  9 14]
 [10 14 12]
 [11 11  7]]

Multiplication of Two matrices
---------------------------------------------------------------------------
[[ 4 20 45]
 [ 9 45 35]
 [30 28 10]]

Matrix 1:
[[9 4 2]
 [8 7 3]
 [6 8 7]
 [1 7 5]]
Matrix 2:
[[7 8]
 [1 9]
 [2 4]]

Element-by-Element Multiplication of Two matrices
---------------------------------------------------------------------------
[[ 71 116]
 [ 69 139]
 [ 64 148]
 [ 24  91]]

Displaying Specific Rows and column
---------------------------------------------------------------------------
[[139]
 [148]
 [ 91]]
