In [1]:
import numpy as np

arr=np.random.randn(4,3)
print('Array:')
print('---------------------------------------------------------------------------')
print(arr)
print()
print('Absolute Value of the Array')
print('---------------------------------------------------------------------------')
print(np.absolute(arr))
print()
print('Negative Value of the Array')
print('---------------------------------------------------------------------------')
print(np.negative(arr))
print()
print('Array after deleting row 2')
print('---------------------------------------------------------------------------')
print(np.delete(arr,2,0))
print()
print('Array after deleting column 2')
print('---------------------------------------------------------------------------')
print(np.delete(arr,2,1))
print()
print('Maximum of Array')
print('---------------------------------------------------------------------------')
print(np.max(arr))
print()
print('Minimum of Array')
print('---------------------------------------------------------------------------')
print(np.min(arr))
print()
print('Sum of all elements of Array')
print('---------------------------------------------------------------------------')
print(np.sum(arr))
print()
print('Sum of all elements of Array row-wise')
print('---------------------------------------------------------------------------')
print(np.sum(arr,0))
print()
print('Sum of all elements of Array column-wise')
print('---------------------------------------------------------------------------')
print(np.sum(arr,1))

Array:
---------------------------------------------------------------------------
[[-0.5771732  -1.55647187 -0.02227878]
 [ 0.5217378  -0.21698528 -0.45267642]
 [-0.77716877 -0.03416114 -0.28532191]
 [-0.17929322 -0.56541161  0.63109234]]

Absolute Value of the Array
---------------------------------------------------------------------------
[[0.5771732  1.55647187 0.02227878]
 [0.5217378  0.21698528 0.45267642]
 [0.77716877 0.03416114 0.28532191]
 [0.17929322 0.56541161 0.63109234]]

Negative Value of the Array
---------------------------------------------------------------------------
[[ 0.5771732   1.55647187  0.02227878]
 [-0.5217378   0.21698528  0.45267642]
 [ 0.77716877  0.03416114  0.28532191]
 [ 0.17929322  0.56541161 -0.63109234]]

Array after deleting row 2
---------------------------------------------------------------------------
[[-0.5771732  -1.55647187 -0.02227878]
 [ 0.5217378  -0.21698528 -0.45267642]
 [-0.17929322 -0.56541161  0.63109234]]

Array after deleting colu