In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print(a)
print(b)


[1 2 3]
[3 4 5]


In [4]:
a*b

array([ 3,  8, 15])

In [6]:
z=np.array([[1,2,3,4.9],[5,6,7,8],[9,10,11,12]])
print(z)

[[ 1.   2.   3.   4.9]
 [ 5.   6.   7.   8. ]
 [ 9.  10.  11.  12. ]]


In [7]:
#get dimensions
z.ndim

2

In [10]:
z.shape

(3, 4)

In [12]:
z.dtype

dtype('float64')

In [14]:
z[:,3]

array([ 4.9,  8. , 12. ])

In [15]:
z[1,:]

array([5., 6., 7., 8.])

In [19]:
z[:,1::2]

array([[ 2. ,  4.9],
       [ 6. ,  8. ],
       [10. , 12. ]])

In [8]:
a.size*a.itemsize

12

In [9]:
a.nbytes

12

In [10]:
p=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [11]:
p[1,2]

8

In [12]:
p[1,-2]

9

In [13]:
p[1][2]

8

In [15]:
p[:,3]=[4,9]

In [16]:
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
s=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [22]:
s

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
print(s)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
s.shape

(2, 2, 2)

In [25]:
s[0,1,1]

4

In [27]:
s[:,1,:]

array([[3, 4],
       [7, 8]])

In [28]:
s[:,1,:]=[[9,9],[9,9]]

In [29]:
s

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [9, 9]]])

In [30]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.ones((2,3),dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [37]:
np.full((2,2),90)

array([[90, 90],
       [90, 90]])

In [39]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
np.random.rand(2,3)

array([[0.22601084, 0.26577941, 0.00715646],
       [0.21425178, 0.34636906, 0.53469683]])

In [42]:
np.random.random_sample(a.shape)

array([0.58302815, 0.88399271, 0.19049923])

In [43]:
np.random.randint(1,7)

6

In [44]:
np.random.randint(7)

2

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
r1.shape

(3, 3)

In [49]:
c=np.array([1,2,3])

In [50]:
n=c
print(n)

[1 2 3]


In [51]:
n[1]=90
print(n)
print(c)

[ 1 90  3]
[ 1 90  3]


In [52]:
c=np.array([1,2,3])
n=c.copy()
print(n)

[1 2 3]


In [53]:
n[0]=90
print(n)
print(c)

[90  2  3]
[1 2 3]


In [54]:
a

array([1, 2, 3])

In [55]:
a+2

array([3, 4, 5])

In [56]:
a-2

array([-1,  0,  1])

In [57]:
a/2

array([0.5, 1. , 1.5])

In [58]:
a*2

array([2, 4, 6])

In [59]:
a**2

array([1, 4, 9], dtype=int32)

In [60]:
v=np.sin(a)

In [61]:
print(v)

[0.84147098 0.90929743 0.14112001]
