In [3]:
import numpy as np
arr=np.random.randn(4,3)
print('Array:')
print('---------------------------------------------------------------------------')
print(arr)
print()
print('Size of Array:')
print('---------------------------------------------------------------------------')
print(arr.size)
print()
print('Size of particular row (row 2):')
print('---------------------------------------------------------------------------')
print(len(arr[:,2]))
print()
print('Size of particular column (column 2):')
print('---------------------------------------------------------------------------')
print(len(arr[2,:]))
print()
print('Taking input from file: ')
print('---------------------------------------------------------------------------')
with open('numpy2text.txt', 'r') as f:
    l =np.loadtxt(f)
print(l)
print()
print('Saving Array to a file: ')
print('---------------------------------------------------------------------------')
with open('numpy2output.txt', 'wb') as f:
    np.savetxt(f,arr)
print("Done!")

Array:
---------------------------------------------------------------------------
[[ 2.70795929  1.18470041  1.69218739]
 [ 1.00750983  0.44321823 -0.30040231]
 [ 1.41514761  0.79850967  0.72488257]
 [ 1.46855347 -0.15461344  3.50905393]]

Size of Array:
---------------------------------------------------------------------------
12

Size of particular row (row 2):
---------------------------------------------------------------------------
4

Size of particular column (column 2):
---------------------------------------------------------------------------
3

Taking input from file: 
---------------------------------------------------------------------------
[ 2.    -3.     4.     5.     2.111]

Saving Array to a file: 
---------------------------------------------------------------------------
Done!
